import { useState, useRef, useEffect } from 'react';
import { Mic, Square, Download, Circle, FileText, Sparkles } from 'lucide-react';
import ProgressIndicator from '../components/ProgressIndicator';

function RealTimeTranscription() {
  const [isRecording, setIsRecording] = useState(false);
  const [transcript, setTranscript] = useState('');
  const [isProcessing, setIsProcessing] = useState(false);
  const [summary, setSummary] = useState('');
  const [downloadEnabled, setDownloadEnabled] = useState(false);

  const mediaRecorderRef = useRef(null);
  const recognitionRef = useRef(null);
  const transcriptRef = useRef('');

  // Initialize Speech Recognition
  useEffect(() => {
    if ('webkitSpeechRecognition' in window || 'SpeechRecognition' in window) {
      const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
      const recognition = new SpeechRecognition();

      recognition.continuous = true;
      recognition.interimResults = true;
      // recognition.lang = 'en-US';
      recognition.lang = 'si-LK'
      recognition.onresult = (event) => {
        let interimTranscript = '';
        let finalTranscript = '';

        for (let i = event.resultIndex; i < event.results.length; i++) {
          const transcript = event.results[i][0].transcript;
          if (event.results[i].isFinal) {
            finalTranscript += transcript + ' ';
          } else {
            interimTranscript += transcript;
          }
        }

        if (finalTranscript) {
          transcriptRef.current += finalTranscript;
          setTranscript(transcriptRef.current + interimTranscript);
        } else {
          setTranscript(transcriptRef.current + interimTranscript);
        }
      };

      recognition.onerror = (event) => {
        console.error('Speech recognition error:', event.error);
      };

      recognitionRef.current = recognition;
    }

    return () => {
      if (recognitionRef.current) {
        recognitionRef.current.stop();
      }
    };
  }, []);

  const startRecording = async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });

      mediaRecorderRef.current = new MediaRecorder(stream);
      mediaRecorderRef.current.start();

      // Start speech recognition
      if (recognitionRef.current) {
        recognitionRef.current.start();
      }

      setIsRecording(true);
      setTranscript('');
      transcriptRef.current = '';
      setSummary('');
      setDownloadEnabled(false);
    } catch (error) {
      console.error('Error accessing microphone:', error);
      alert('Could not access microphone. Please check permissions.');
    }
  };

  const stopRecording = () => {
    if (mediaRecorderRef.current && mediaRecorderRef.current.state !== 'inactive') {
      mediaRecorderRef.current.stop();
      mediaRecorderRef.current.stream.getTracks().forEach(track => track.stop());
    }

    if (recognitionRef.current) {
      recognitionRef.current.stop();
    }

    setIsRecording(false);

    // Simulate transcript correction and summarization
    if (transcriptRef.current.trim()) {
      setIsProcessing(true);

      setTimeout(() => {
        // Simulate transcript correction
        const correctedTranscript = transcriptRef.current.trim();
        setTranscript(correctedTranscript);

        // Simulate summary generation
        const generatedSummary = generateMockSummary(correctedTranscript);
        setSummary(generatedSummary);

        setIsProcessing(false);
        setDownloadEnabled(true);
      }, 2000);
    }
  };

  const generateMockSummary = (text) => {
    // Mock summary generation - in real app, this would call your backend API
    const words = text.split(' ').length;
    return `Summary of Lecture:\n\nTotal words transcribed: ${words}\n\nKey Points:\n• Main topic discussed\n• Important concepts covered\n• Conclusions reached\n\n[This is a mock summary. In production, this would be generated by your AI model.]`;
  };

  const downloadFiles = () => {
    // Download transcript
    const transcriptBlob = new Blob([transcript], { type: 'text/plain' });
    const transcriptUrl = URL.createObjectURL(transcriptBlob);
    const transcriptLink = document.createElement('a');
    transcriptLink.href = transcriptUrl;
    transcriptLink.download = `lecture-transcript-${Date.now()}.txt`;
    document.body.appendChild(transcriptLink);
    transcriptLink.click();
    document.body.removeChild(transcriptLink);
    URL.revokeObjectURL(transcriptUrl);

    // Download summary
    const summaryBlob = new Blob([summary], { type: 'text/plain' });
    const summaryUrl = URL.createObjectURL(summaryBlob);
    const summaryLink = document.createElement('a');
    summaryLink.href = summaryUrl;
    summaryLink.download = `lecture-summary-${Date.now()}.txt`;
    document.body.appendChild(summaryLink);
    summaryLink.click();
    document.body.removeChild(summaryLink);
    URL.revokeObjectURL(summaryUrl);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-sky-50 to-cyan-50 p-4 sm:p-6 lg:p-8">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-blue-500 rounded-full mb-4">
            <Mic className="w-8 h-8 text-white" />
          </div>
          <h1 className="text-2xl sm:text-3xl font-bold text-gray-800 mb-2">Real-Time Transcription</h1>
          <p className="text-sm sm:text-base text-gray-600">Record your lecture and get instant transcription</p>
        </div>

        {/* Control Card */}
        <div className="bg-white rounded-2xl shadow-lg p-6 sm:p-8 mb-6">
          {/* Recording Status */}
          {isRecording && (
            <div className="mb-6 bg-gradient-to-r from-red-50 to-pink-50 rounded-xl p-4 border border-red-200">
              <div className="flex items-center justify-center gap-3">
                <Circle className="w-3 h-3 text-red-500 fill-current animate-pulse" />
                <span className="text-sm sm:text-base font-semibold text-red-600">Recording in progress...</span>
              </div>
            </div>
          )}

          {/* Control Buttons */}
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-6">
            {!isRecording ? (
              <button
                onClick={startRecording}
                className="w-full sm:w-auto flex items-center justify-center gap-3 px-6 sm:px-8 py-3 sm:py-4 bg-gradient-to-r from-blue-500 to-cyan-500 text-white rounded-xl font-semibold shadow-lg hover:shadow-xl hover:scale-105 transition-all"
              >
                <Mic className="w-5 h-5" />
                Start Recording
              </button>
            ) : (
              <button
                onClick={stopRecording}
                className="w-full sm:w-auto flex items-center justify-center gap-3 px-6 sm:px-8 py-3 sm:py-4 bg-gradient-to-r from-red-500 to-pink-500 text-white rounded-xl font-semibold shadow-lg hover:shadow-xl hover:scale-105 transition-all"
              >
                <Square className="w-5 h-5" />
                Stop Recording
              </button>
            )}

            <button
              onClick={downloadFiles}
              disabled={!downloadEnabled}
              className={`w-full sm:w-auto flex items-center justify-center gap-3 px-6 sm:px-8 py-3 sm:py-4 rounded-xl font-semibold shadow-lg transition-all ${downloadEnabled
                ? 'bg-gradient-to-r from-green-500 to-emerald-500 text-white hover:shadow-xl hover:scale-105'
                : 'bg-gray-200 text-gray-400 cursor-not-allowed'
                }`}
            >
              <Download className="w-5 h-5" />
              Download
            </button>
          </div>

          {/* Processing */}
          {isProcessing && (
            <div className="bg-gradient-to-r from-blue-50 to-cyan-50 rounded-xl p-4 border border-blue-200">
              <ProgressIndicator message="Processing transcript..." />
            </div>
          )}
        </div>

        {/* Transcript Card */}
        <div className="bg-white rounded-2xl shadow-lg p-6 sm:p-8 mb-6">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-10 h-10 bg-blue-100 rounded-lg flex items-center justify-center">
              <FileText className="w-5 h-5 text-blue-500" />
            </div>
            <div className="flex-1">
              <h3 className="text-lg sm:text-xl font-bold text-gray-800">Live Transcript</h3>
              <p className="text-xs sm:text-sm text-gray-500">
                {transcript ? `${transcript.split(' ').length} words` : 'Waiting for audio...'}
              </p>
            </div>
          </div>
          <div className="bg-gray-50 rounded-xl p-4 sm:p-6 min-h-48 max-h-64 sm:max-h-96 overflow-y-auto">
            {transcript ? (
              <p className="text-sm sm:text-base text-gray-700 whitespace-pre-wrap leading-relaxed">
                {transcript}
              </p>
            ) : (
              <div className="flex flex-col items-center justify-center h-40 text-center">
                <Circle className="w-12 h-12 text-gray-300 mb-3" />
                <p className="text-sm sm:text-base text-gray-400">Click "Start Recording" to begin</p>
              </div>
            )}
          </div>
        </div>

        {/* Summary Card */}
        {summary && (
          <div className="bg-gradient-to-br from-blue-50 to-cyan-50 rounded-2xl shadow-lg p-6 sm:p-8 border border-blue-100">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 bg-blue-500 rounded-lg flex items-center justify-center">
                <Sparkles className="w-5 h-5 text-white" />
              </div>
              <div className="flex-1">
                <h3 className="text-lg sm:text-xl font-bold text-gray-800">Summary</h3>
                <p className="text-xs sm:text-sm text-gray-600">{summary.split(' ').length} words</p>
              </div>
            </div>
            <div className="bg-white rounded-xl p-4 sm:p-6">
              <p className="text-sm sm:text-base text-gray-700 whitespace-pre-wrap leading-relaxed">
                {summary}
              </p>
            </div>
          </div>
        )}
      </div>
      {/* Info Card */}
      <div className="bg-blue-50 rounded-lg p-4 border border-blue-200">
        <h3 className="font-semibold text-blue-900 mb-2">ℹ️ How it works:</h3>
        <ul className="text-sm text-blue-800 space-y-1 list-disc list-inside">
          <li>Click "Start Recording" and allow microphone access</li>
          <li>Speak clearly into your microphone</li>
          <li>See real-time transcription in the box above</li>
          <li>Click "Stop Recording" when finished</li>
          <li>Download your notes as a text file</li>
        </ul>
        <p className="text-xs text-blue-700 mt-3">
          <strong>Note:</strong> This demo uses mock data. In production, integrate with speech-to-text APIs
          (OpenAI Whisper, Google Speech-to-Text, AssemblyAI) and AI summarization services.
        </p>
      </div>
    </div>
  );
}

export default RealTimeTranscription;